name: Bump version and auto-release
on:
  push:
    branches:
      - main
    paths-ignore:
    - "**/README.md" # ignores all README files
    - "**/workflows/release.yaml" # ignore changes to this file itself

jobs:
  release:
    uses: openclimatefix/.github/.github/workflows/docker-release.yml@v1.7.2
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
    with:
      image_base_name: pvnet_app